<? 
//////////////////////////////////
//       TheRandomizer script   //
//       Version 2.0            //
// By ITWebTeam-www.ITWebTeam.net/
//You can edit here the main    //
//    settings for the site     //
//////////////////////////////////
class Object {

//////////////////////////////////
//        Script Paths          //
//////////////////////////////////
public $wwwroot     = "/home4/myguaran/public_html/";
//Site URL -please use the "https://www.ez-moneymaker.com" format.
public $siteurl     = "https://www.ez-moneymaker.com";
//Edit below ONLY if you changed the current site structure
public $templatedir = "$wwwroot/templates";
public $libdir      = "$wwwroot/lib";
public $imagedir    = "$CONFIG->wwwroot/rimages";
//////////////////////////////////
//      Site look               //
//////////////////////////////////
// show the text ads in header or footer
public $header_textads=true;
public $header_banners=true;
public $footer_textads=false;


                      public $cb_footer_textads=true;



public $footer_banners=true;
public $colorscheme  = "nice_blue";
//Color scheme: choose between nice_blue,almost_green,fresh,sunny
//ENTER "custom" if you want to define your own color scheme.
/////////////////////////////////////
//          CUSTOM COLOR SCHEME    //
//                                 //
public $darkcolor="#336699";
public $bgcolor="#C0C0C0";
public $lightcolor="#9DC7F2";
//                                 //
//    END OF CUSTOM COLOR SCHEME   //
/////////////////////////////////////
//
public $showstats=false;//show the site stats on the left side
//////////////////////////////////
//       Site Details           //
//////////////////////////////////

// The support email address-all the mails from the contact form will go there
public $support     = "admin@ez-moneymaker.com";

//Site name-this will be shown on the header,and footer,and also on every email sent
public $sitename    = "EZ-MoneyMaker.com";

//Item Name for the payments
public $paymentnote="Membership";


//Item Number for the payments
public $paymentnote2="EZ-MoneyMaker.com";

/* The next variable sets who will be paid if there is no referral(sponsor)
    Set it to false,if you want the admin to receive the payment or to true if
     you want a random member to be chosen
*/
public $payrandom    = false;


/////////////////////////////////////
//          EMAIL NOTIFICATION     //
//    set the next variable true   //
//to receive email notifications   //
//       of new signups            //
//                                 //
public $sendemail=true;
//Send email to:                   //
public $sendto="admin@ez-moneymaker.com";
//                                 //
//    END OF EMAIL NOTIFICATION    //
/////////////////////////////////////
/////////////////////////////////////
//         Payment Fees            //
//    Use the same format          //
//              XX.XX              //
public $adminfee="25.00";

//for sponsor
public $sponsorfee="25.00";

//for random membbers
public $randomfee="0.00";



               public $sponsorfee_free="10.00";
               public $adminfee_free="40.00";



//Weight parameters:
public $weight2="5.00";//    2 new chances
public $weight5="15.00";//   5 more chances
public $weight10="25.00";//  10 more chances
public $weight15="39.00";//   15 more chances
public $weight25="55.00";//   25 more chances
public $weight50="85.00";//   50 more chances
public $weight100="140.00";//   100 more chances
public $weight250="200.00";//   200 more chances


//                                           Payment processors
//Change TRUE with FALSE if you don't want to use one of them.
public $allowpaypal=false;
public $allowstormpay=false;
public $allowegold=false;
public $allowlibertyreserve=false;
public $allowassuredpay=false;
public $allowsolidtrustpay=true;
public $allowfleetpay=false;
public $allowdollardeliverys=false;
public $allowmoneybookers=false;



 /////////////////////////////////////////
//                AFFILIATE ID           //
//Starting with the 2.0 version,         //
//you can earn money with your site      //
//promoting TheRandomizer script         //
//Enter your TheRandomizer.net username  //
public $affiliateusername="username";
//and LEAVE the "Powered by" intact      //
//you will earn 10% from every sale      //
//generated by you...                    //
 /////////////////////////////////////////


/*             READY !!!
*             Do NOT  EDIT BELOW!!!
*       OPEN THE INSTALL.PHP FILE IN YOUR BROWSER NOW
                                    */
public $primu=$siteurl."/join.php?stage=primu";
public $adminul=$siteurl."/join.php?stage=adminul";
public $complete=$siteurl."/rusers/final.php";

public $add2=$siteurl."/rusers/weight_finish.php?cat"."=2";
public $add5=$siteurl."/rusers/weight_finish.php?cat"."=5";
public $add10=$siteurl."/rusers/weight_finish.php?cat"."=10";
public $add15=$siteurl."/rusers/weight_finish.php?cat"."=15";
public $add25=$siteurl."/rusers/weight_finish.php?cat"."=25";
public $add50=$siteurl."/rusers/weight_finish.php?cat"."=50";
public $add100=$siteurl."/rusers/weight_finish.php?cat"."=100";
public $add250=$siteurl."/rusers/weight_finish.php?cat"."=250";

}


/* load up standard libraries */

?>
