<? 
//////////////////////////////////
//       TheRandomizer script   //
//       Version 2.0            //
// By ITWebTeam-www.ITWebTeam.net/
//You can edit here the main    //
//    settings for the site     //
//////////////////////////////////
class object {};
$CONFIG = new object;
//////////////////////////////////
//        Script Paths          //
//////////////////////////////////
$CONFIG->wwwroot     = "/home4/myguaran/public_html/";
//Site URL -please use the "https://www.ez-moneymaker.com" format.
$CONFIG->siteurl     = "https://www.ez-moneymaker.com";
//Edit below ONLY if you changed the current site structure
$CONFIG->templatedir = "$CONFIG->wwwroot/templates";
$CONFIG->libdir      = "$CONFIG->wwwroot/lib";
$CONFIG->imagedir    = "$CONFIG->wwwroot/rimages";
//////////////////////////////////
//      Site look               //
//////////////////////////////////
// show the text ads in header or footer
$CONFIG->header_textads=true;
$CONFIG->header_banners=true;
$CONFIG->footer_textads=false;


                       $CONFIG->cb_footer_textads=true;



$CONFIG->footer_banners=true;
$CONFIG->colorscheme  = "nice_blue";
//Color scheme: choose between nice_blue,almost_green,fresh,sunny
//ENTER "custom" if you want to define your own color scheme.
/////////////////////////////////////
//          CUSTOM COLOR SCHEME    //
//                                 //
$CONFIG->darkcolor="#336699";
$CONFIG->bgcolor="#C0C0C0";
$CONFIG->lightcolor="#9DC7F2";
//                                 //
//    END OF CUSTOM COLOR SCHEME   //
/////////////////////////////////////
//
$CONFIG->showstats=false;//show the site stats on the left side
//////////////////////////////////
//       Site Details           //
//////////////////////////////////

// The support email address-all the mails from the contact form will go there
$CONFIG->support     = "admin@ez-moneymaker.com";

//Site name-this will be shown on the header,and footer,and also on every email sent
$CONFIG->sitename    = "EZ-MoneyMaker.com";

//Item Name for the payments
$CONFIG->paymentnote="Membership";


//Item Number for the payments
$CONFIG->paymentnote2="EZ-MoneyMaker.com";

/* The next variable sets who will be paid if there is no referral(sponsor)
    Set it to false,if you want the admin to receive the payment or to true if
     you want a random member to be chosen
*/
$CONFIG->payrandom    = false;


/////////////////////////////////////
//          EMAIL NOTIFICATION     //
//    set the next variable true   //
//to receive email notifications   //
//       of new signups            //
//                                 //
$CONFIG->sendemail=true;
//Send email to:                   //
$CONFIG->sendto="admin@ez-moneymaker.com";
//                                 //
//    END OF EMAIL NOTIFICATION    //
/////////////////////////////////////
/////////////////////////////////////
//         Payment Fees            //
//    Use the same format          //
//              XX.XX              //
$CONFIG->adminfee="25.00";

//for sponsor
$CONFIG->sponsorfee="25.00";

//for random membbers
$CONFIG->randomfee="0.00";



               $CONFIG->sponsorfee_free="10.00";
               $CONFIG->adminfee_free="40.00";



//Weight parameters:
$CONFIG->weight2="5.00";//    2 new chances
$CONFIG->weight5="15.00";//   5 more chances
$CONFIG->weight10="25.00";//  10 more chances
$CONFIG->weight15="39.00";//   15 more chances
$CONFIG->weight25="55.00";//   25 more chances
$CONFIG->weight50="85.00";//   50 more chances
$CONFIG->weight100="140.00";//   100 more chances
$CONFIG->weight250="200.00";//   200 more chances


//                                           Payment processors
//Change TRUE with FALSE if you don't want to use one of them.
$CONFIG->allowpaypal=false;
$CONFIG->allowstormpay=false;
$CONFIG->allowegold=false;
$CONFIG->allowlibertyreserve=false;
$CONFIG->allowassuredpay=false;
         $CONFIG->allowsolidtrustpay=true;
$CONFIG->allowfleetpay=false;
$CONFIG->allowdollardeliverys=false;
$CONFIG->allowmoneybookers=false;



 /////////////////////////////////////////
//                AFFILIATE ID           //
//Starting with the 2.0 version,         //
//you can earn money with your site      //
//promoting TheRandomizer script         //
//Enter your TheRandomizer.net username  //
$CONFIG->affiliateusername="username";
//and LEAVE the "Powered by" intact      //
//you will earn 10% from every sale      //
//generated by you...                    //
 /////////////////////////////////////////


/*             READY !!!
*             Do NOT  EDIT BELOW!!!
*       OPEN THE INSTALL.PHP FILE IN YOUR BROWSER NOW
                                    */
$CONFIG->primu=$CONFIG->siteurl."/join.php?stage=primu";
$CONFIG->adminul=$CONFIG->siteurl."/join.php?stage=adminul";
$CONFIG->complete=$CONFIG->siteurl."/rusers/final.php";

$CONFIG->add2=$CONFIG->siteurl."/rusers/weight_finish.php?cat"."=2";
$CONFIG->add5=$CONFIG->siteurl."/rusers/weight_finish.php?cat"."=5";
$CONFIG->add10=$CONFIG->siteurl."/rusers/weight_finish.php?cat"."=10";
$CONFIG->add15=$CONFIG->siteurl."/rusers/weight_finish.php?cat"."=15";
$CONFIG->add25=$CONFIG->siteurl."/rusers/weight_finish.php?cat"."=25";
$CONFIG->add50=$CONFIG->siteurl."/rusers/weight_finish.php?cat"."=50";
$CONFIG->add100=$CONFIG->siteurl."/rusers/weight_finish.php?cat"."=100";
$CONFIG->add250=$CONFIG->siteurl."/rusers/weight_finish.php?cat"."=250";

/* load up standard libraries */
require("$CONFIG->libdir/stdlib.php");
require("$CONFIG->libdir/dblib.php");
require("$CONFIG->libdir/genlib.php");
session_start();
session_register("sponsor");
session_register("random");
/* connect to the database */
require_once("db_connect.php");
require_once("$CONFIG->libdir/general.php");
?>
